export const categories = ['learning', 'inspiration']

export const books = [
  {
    id: 1,
    title: 'The nature of code',
    subtitle: 'Simulating natural systems with Processing',
    authors: ['Daniel Schiffman'],
    publishers: ['Self-published'],
    language: 'English',
    date: 2012,
    pages: 499,
    category: 'learning',
    tags: [
      'programming',
      'creative code',
      'mathematics',
      'processing',
      'theory',
      'practice',
    ],
  },
  {
    id: 2,
    title: 'Make ink',
    subtitle: "A forager's guide to natural inkmaking",
    authors: ['Jason Logan'],
    publishers: ['Abrams'],
    language: 'English',
    date: 2018,
    pages: 192,
    category: 'learning',
    tags: [
      'DIY',
      'crafts',
      'art',
      'biochemistry',
      'dyeing',
      'practice',
      'theory',
      'color',
    ],
  },
  {
    id: 3,
    title: 'Hands on',
    subtitle: 'Interactive design in print',
    authors: ['viction:ary'],
    publishers: ['viction:workshop'],
    language: 'English',
    date: 2013,
    pages: 242,
    category: 'inspiration',
    tags: ['graphic design', 'interactivity', 'print'],
  },
  {
    id: 4,
    title: 'Graphic design in the post-digital age',
    subtitle: 'A survey of practices fuelled by creative coding',
    authors: ['Demian Conrad', 'Silvio Lorusso'],
    publishers: ['Onomatopee', 'HEAD Genève'],
    language: 'English',
    date: 2021,
    pages: 608,
    category: 'learning',
    tags: ['graphic design', 'creative code', 'research', 'digital', 'theory'],
  },
  {
    id: 5,
    title: 'More is more',
    subtitle: 'Designing bigger, bolder, brighter',
    authors: ['viction:ary'],
    publishers: ['viction:workshop'],
    language: 'English',
    date: 2021,
    pages: 285,
    category: 'inspiration',
    tags: ['graphic design', 'print', 'identity', 'poster'],
  },
  {
    id: 6,
    title: 'Textilepedia',
    subtitle: 'The complete fabric guide',
    authors: ['Fashionary'],
    publishers: ['Fashionary International'],
    language: 'English',
    date: 2021,
    pages: 250,
    category: 'learning',
    tags: ['textile', 'weaving', 'practice', 'theory'],
  },
  {
    id: 7,
    title: 'Morphing',
    subtitle:
      'A guide to mathematicals transformations for architects and designers',
    authors: ['Joseph Choma'],
    publishers: ['King Publishing'],
    language: 'English',
    date: 2015,
    pages: 250,
    category: 'learning',
    tags: [
      'mathematics',
      'geometry',
      '3D',
      'programming',
      'creative code',
      'theory',
      'practice',
    ],
  },
  {
    id: 8,
    title: "The world's favourite colour project",
    subtitle: 'A global research study investigating the psychology of colour',
    authors: ['G.F. Smith'],
    publishers: ['G.F Smith & Son'],
    language: 'English',
    date: 2019,
    pages: 172,
    category: 'learning',
    tags: [
      'graphic design',
      'color',
      'theory',
      'research',
      'psychology',
      'print',
      'printing',
      'paper',
    ],
  },
  {
    id: 9,
    title: 'Taking a line for a walk',
    subtitle: 'Assignments in design education',
    authors: ['Nina Paim', 'Corinne Gisel', 'Emilia Bergmark'],
    publishers: ['Spector Books'],
    language: 'English',
    date: 2016,
    pages: 276,
    category: 'learning',
    tags: ['art', 'design', 'theory', 'pedagogy'],
  },
  {
    id: 10,
    title: 'Exploriso: low-tech fine art',
    subtitle: 'Risography as an artistic Process',
    authors: ['Sven Tillack'],
    publishers: ['Spector Books'],
    language: 'English',
    date: 2021,
    pages: 184,
    category: 'learning',
    tags: ['graphic design', 'print', 'printing', 'art'],
  },
  {
    id: 11,
    title: 'Playful graphics',
    subtitle: 'Unexpected graphic design',
    authors: ['Shaoqiang Wang'],
    publishers: ['Promopress'],
    language: 'English',
    date: 2020,
    pages: 240,
    category: 'inspiration',
    tags: ['graphic design', 'interactivity', 'print'],
  },
  {
    id: 12,
    title: 'Essential mathematics for games and interactive applications',
    subtitle: '',
    authors: ['James M. Van Verth', 'Lars M. Bishop'],
    publishers: ['Apple Academic Press Inc.'],
    language: 'English',
    date: 2015,
    pages: 592,
    category: 'learning',
    tags: ['game', 'mathematics', '3D', 'animation', 'theory', 'practice'],
  },
  {
    id: 13,
    title: 'Modern Software Engineering',
    subtitle: 'Doing what works to build better software faster',
    authors: ['David Farley'],
    publishers: ['Pearson Education'],
    language: 'English',
    date: 2022,
    pages: 256,
    category: 'learning',
    tags: ['software engineering', 'practice', 'theory'],
  },
  {
    id: 14,
    title: 'Wicked arts assignments',
    subtitle: 'Practising creativity in contemporary arts education',
    authors: ['Emiel Heijnen', 'Melissa Bremmer'],
    publishers: ['Valiz'],
    language: 'English',
    date: 2021,
    pages: 304,
    category: 'learning',
    tags: ['art', 'pedagogy', 'theory'],
  },
  {
    id: 15,
    title: 'Applied cryptography',
    subtitle: 'Protocols, algorithms, and source code in C',
    authors: ['Bruce Schneier'],
    publishers: ['John Wiley & Sons Inc'],
    language: 'English',
    date: 1995,
    pages: 792,
    category: 'learning',
    tags: [
      'programming',
      'computer science',
      'mathematics',
      'security',
      'cryptography',
      'C',
      'practice',
      'theory',
    ],
  },
  {
    id: 16,
    title: 'Hacking',
    subtitle: 'The art of exploration',
    authors: ['Jon Erickson'],
    publishers: ['No Starch Press'],
    language: 'English',
    date: 2008,
    pages: 488,
    category: 'learning',
    tags: ['programming', 'security', 'C', 'hacking', 'practice'],
  },
  {
    id: 17,
    title: 'Handmade electronic music',
    subtitle: 'The art of hardware hacking',
    authors: ['Nicolas Collins'],
    publishers: ['Taylor & Francis'],
    language: 'English',
    date: 2020,
    pages: 434,
    category: 'learning',
    tags: ['music', 'electronics', 'hacking', 'DIY', 'practice', 'theory'],
  },
  {
    id: 18,
    title: 'Computer networking',
    subtitle: 'A top-down approach',
    authors: ['James Kurose', 'Keith Ross'],
    publishers: ['Pearson Education'],
    language: 'English',
    date: 2021,
    pages: 856,
    category: 'learning',
    tags: ['computer science', 'software engineering', 'networking', 'theory'],
  },
  {
    id: 19,
    title: 'The C programming language',
    subtitle: 'ANSI C',
    authors: ['Brian Kernighan', 'Dennis Ritchie'],
    publishers: ['Pearson Education'],
    language: 'English',
    date: 1988,
    pages: 288,
    category: 'learning',
    tags: [
      'programming',
      'computer science',
      'software engineering',
      'C',
      'theory',
      'practice',
    ],
  },
  {
    id: 20,
    title: 'Expert C programming',
    subtitle: 'Deep C secrets',
    authors: ['Peter Van Der Linden'],
    publishers: ['Pearson Education'],
    language: 'English',
    date: 1994,
    pages: 380,
    category: 'learning',
    tags: [
      'programming',
      'computer science',
      'software engineering',
      'C',
      'theory',
      'practice',
    ],
  },
  {
    id: 21,
    title: "Beej's Guide to Network Programming",
    subtitle: 'Using Internet Sockets',
    authors: ['Brian "Beej Jorgensen" Hall'],
    publishers: ['Self-published'],
    language: 'English',
    date: 2019,
    pages: 174,
    category: 'learning',
    tags: [
      'programming',
      'computer science',
      'software engineering',
      'C',
      'theory',
      'practice',
      'networking',
    ],
  },
  {
    id: 22,
    title: 'The Complete Rust Programming Reference Guide',
    subtitle:
      'Design, develop, and deploy effective software systems using the advanced constructs of Rust',
    authors: ['Rahul Sharma', 'Vesa Kaihlavirta', 'Claus Matzinger'],
    publishers: ['Packt'],
    language: 'English',
    date: 2019,
    pages: 698,
    category: 'learning',
    tags: [
      'programming',
      'computer science',
      'software engineering',
      'Rust',
      'theory',
      'practice',
    ],
  },
  {
    id: 23,
    title: 'A Touch of code',
    subtitle: 'Interactive installations and experiences',
    authors: [' Robert Klanten'],
    publishers: ['Die Gestalten Verlag'],
    language: 'English',
    date: 2011,
    pages: 240,
    category: 'inspiration',
    tags: [
      'programming',
      'design',
      'creative code',
      'interactivity',
      'digital',
    ],
  },
  {
    id: 24,
    title: 'On the road to variable',
    subtitle: 'The flexible future of typography',
    authors: ['TwoPoints.net'],
    publishers: ['viction:workshop'],
    language: 'English',
    date: 2019,
    pages: 264,
    category: 'inspiration',
    tags: ['graphic design', 'typography', 'digital'],
  },
  {
    id: 25,
    title: 'Graphic fest',
    subtitle: 'Identities for festivals & fairs',
    authors: ['viction:ary'],
    publishers: ['viction:workshop'],
    language: 'English',
    date: 2019,
    pages: 256,
    category: 'inspiration',
    tags: ['graphic design', 'typography', 'identity', 'poster'],
  },
  {
    id: 26,
    title: 'Material matters 04: Paper',
    subtitle: 'Creative interpretations of common materials',
    authors: ['viction:ary'],
    publishers: ['viction:workshop'],
    language: 'English',
    date: 2019,
    pages: 160,
    category: 'inspiration',
    tags: ['graphic design', 'print', 'paper'],
  },
  {
    id: 27,
    title: 'Digital by design',
    subtitle: 'Crafting technology for products and environments',
    authors: ['Troika', 'Conny Freyer', 'Sebastien Noel', 'Eva Rucki'],
    publishers: ['Thames & Hudson'],
    language: 'English',
    date: 2011,
    pages: 304,
    category: 'inspiration',
    tags: ['design', 'digital', 'art', 'interactivity'],
  },
  {
    id: 28,
    title: 'Palette 02: Multicolour',
    subtitle: 'New rainbow-hued graphics',
    authors: ['viction:ary'],
    publishers: ['viction:workshop'],
    language: 'English',
    date: 2016,
    pages: 256,
    category: 'inspiration',
    tags: ['graphic design', 'identity', 'color'],
  },
  {
    id: 29,
    title: 'Palette 04: Neon',
    subtitle: 'New fluorescent graphics',
    authors: ['viction:ary'],
    publishers: ['viction:workshop'],
    language: 'English',
    date: 2014,
    pages: 256,
    category: 'inspiration',
    tags: ['graphic design', 'identity'],
  },
  {
    id: 30,
    title: 'Palette 05: Pastel',
    subtitle: 'New soft-toned graphics',
    authors: ['viction:ary'],
    publishers: ['viction:workshop'],
    language: 'English',
    date: 2014,
    pages: 256,
    category: 'inspiration',
    tags: ['graphic design', 'identity'],
  },
  {
    id: 31,
    title: 'Print matters',
    subtitle: 'The Cutting Edge of Print',
    authors: ['viction:ary'],
    publishers: ['viction:workshop'],
    language: 'English',
    date: 2015,
    pages: 288,
    category: 'inspiration',
    tags: ['graphic design', 'identity', 'print'],
  },
  {
    id: 32,
    title: 'Programming interactivity',
    subtitle: "A designer's guide to Processing, Arduino, and openFrameworks",
    authors: [' Joshua Noble'],
    publishers: ["O'Reilly"],
    language: 'English',
    date: 2012,
    pages: 678,
    category: 'learning',
    tags: [
      'design',
      'DIY',
      'interactivity',
      'creative code',
      'programming',
      'electronics',
      'arduino',
      'processing',
      'C++',
      'theory',
      'practice',
    ],
  },
  {
    id: 33,
    title: 'Practical electronics for inventors',
    subtitle: '',
    authors: ['Paul Scherz', 'Simon Monk'],
    publishers: ['McGraw-Hill Education'],
    language: 'English',
    date: 2016,
    pages: 1056,
    category: 'learning',
    tags: ['electronics', 'DIY', 'theory', 'practice'],
  },
  {
    id: 34,
    title: 'Karel Martens: Re-printed matters',
    subtitle: '',
    authors: ['Karel Martens', 'Jaap Van Triest'],
    publishers: ['Roma'],
    language: 'English',
    date: 2019,
    pages: 280,
    category: 'inspiration',
    tags: ['art', 'graphic design', 'print', 'printing', 'paper'],
  },
  {
    id: 35,
    title: 'Poemotion',
    subtitle: '',
    authors: ['Takahiro Kurashima', 'Junji Hata'],
    publishers: ['Lars Müller'],
    language: 'English',
    date: 2012,
    pages: 64,
    category: 'inspiration',
    tags: ['art', 'graphic design', 'interactivity', 'print'],
  },
]

export const tags = [
  ...new Set(books.flatMap((book) => book.tags.map((tag) => tag))),
]

// do subcategories ?
// add ISBN ?
