export const categories = ['learning', 'inspiration']

export const books = [
  {
    id: 1,
    title: 'The nature of code',
    subtitle: 'Simulating natural systems with Processing',
    authors: ['Daniel Schiffman'],
    publishers: ['Self-published'],
    language: 'English',
    date: 2012,
    pages: 499,
    category: 'learning',
    tags: [
      'programming',
      'creative code',
      'mathematics',
      'processing',
      'theory',
      'practice',
    ],
  },
  {
    id: 2,
    title: 'Make ink',
    subtitle: "A forager's guide to natural inkmaking",
    authors: ['Jason Logan'],
    publishers: ['Abrams'],
    language: 'English',
    date: 2018,
    pages: 192,
    category: 'learning',
    tags: [
      'DIY',
      'crafts',
      'art',
      'biochemistry',
      'dyeing',
      'practice',
      'theory',
      'color',
    ],
  },
  {
    id: 3,
    title: 'Hands on',
    subtitle: 'Interactive design in print',
    authors: ['viction:ary'],
    publishers: ['viction:workshop'],
    language: 'English',
    date: 2013,
    pages: 242,
    category: 'inspiration',
    tags: ['graphic design', 'interaction', 'print'],
  },
  {
    id: 4,
    title: 'Graphic design in the post-digital age',
    subtitle: 'A survey of practices fuelled by creative coding',
    authors: ['Demian Conrad', 'Silvio Lorusso'],
    publishers: ['Onomatopee', 'HEAD Genève'],
    language: 'English',
    date: 2021,
    pages: 608,
    category: 'learning',
    tags: ['graphic design', 'creative code', 'research', 'digital art'],
  },
]

export const tags = [
  ...new Set(books.flatMap((book) => book.tags.map((tag) => tag))),
]
